### ISSUE TITLE
[Solved] Unable to Initialize Unity Engine

### ISSUE THREAD

**Issue by firdiar-mita** [jelte/be.khepri.play.assetdelivery.addressables#76]
![WhatsApp Image 2023-12-14 at 12 21 48_1aa8751e](https://github.com/jelte/be.khepri.play.assetdelivery.addressables/assets/147171097/0f300f68-0998-45bd-ada8-c3d77afa2e6e)

the aab content is fine
![image](https://github.com/jelte/be.khepri.play.assetdelivery.addressables/assets/147171097/8f7c70f0-1774-4818-9358-ca18859a358e)

and this is my setting group
![image](https://github.com/jelte/be.khepri.play.assetdelivery.addressables/assets/147171097/2cf37bb7-70e0-4f23-9722-616ed99e43da)

any idea?

**Comment by firdiar-mita** [comment]
got this error
2023/12/14 12:44:55.405 18428 19174 Error Finsky [706] kwb.a(847): Request execution failed with error code: -2
2023/12/14 12:44:55.405 18428 19174 Error Finsky com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at jme.aeT(PG:533)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at jrv.k(PG:75)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at itj.run(PG:70)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at android.os.Handler.handleCallback(Handler.java:942)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at android.os.Handler.dispatchMessage(Handler.java:99)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at android.os.Looper.loopOnce(Looper.java:210)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at android.os.Looper.loop(Looper.java:299)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at android.app.ActivityThread.main(ActivityThread.java:8123)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at java.lang.reflect.Method.invoke(Native Method)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
2023/12/14 12:44:55.405 18428 19174 Error Finsky 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by firdiar-mita** [comment]
but i got all the packet inbundle, and verified here
![image](https://github.com/jelte/be.khepri.play.assetdelivery.addressables/assets/147171097/cb46f89a-77eb-4180-87ef-faa794046995)

**Comment by firdiar-mita** [comment]
i fixed it by changing app compression from LZ4 to Default
